### ISSUE TITLE
Typo (?) in copyright statement

### ISSUE THREAD

**Issue by qmfrederik** [Kajabity/Kajabity-Tools#1]
All the source files start with:

```
Copyright 2009-15 Williams Technologies Limtied.
```

I'm assuming that Limtied is a misspelling of Limited. Can you please confirm that?

Thanks!

**Comment by Kajabity** [comment]
Yes, you are correct - I will update the source code and upload this evening (UK time).  

I have fixed a couple of other minor defects as well and enabled the "Quote" character to be changed so these may benefit any other interested users.

Thanks.

**Comment by Kajabity** [comment]
Pushed 'next-release' branch with corrected spelling and fix to NPE when saving before new/open file.

**Comment by stackh34p** [comment]
Hi,

I also managed to get over a couple of other similar typos in my [pull-request](https://github.com/Kajabity/Kajabity-Tools/pull/3)

Cheers

**Comment by Kajabity** [comment]
I fixed all the 'Limited' mis-spellings in the latest master commit.

**Comment by Elizzy22** [comment]
My account was hacked and I lost almost everything $560,000 I have saved over the years until I found a legit hacker who helped me recover a lot of money in 3 days it was a surprise to me because I do not believe that one can hack money from account just with the bank and front picture of the credit or debit card without holding the card or asking for more details this was the best experience ever if you have a credit of debit card with good funds and you are ready to transfer the money to your personal account without any trace and you can invest in any business of your choice and enjoy life to the fullest here is the contact of the best hacker in the world I call him GURU
contact him here=  monitorywizard247 @ gmail com or whatsapp +19172750978
